# -*- coding: utf-8 -*-
"""匿名地址.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPX9lSAMJdJEV8lexHGezjonY5AiKIcI
"""

import pandas as pd

df_raw = pd.read_csv('.csv', skiprows=3, header=None)

target_row_index = 0
for i in range(len(df_raw)):
    if '客戶編號' in df_raw.iloc[i].astype(str).values:
        target_row_index = i
        break

df = df_raw.iloc[target_row_index + 1:].copy()
df.columns = df_raw.iloc[target_row_index].astype(str).values

df.columns = [col if col != 'nan' else f'Unnamed_{i}' for i, col in enumerate(df.columns)]


df.reset_index(drop=True, inplace=True)
df['Customer_ID'] = ['VIP_' + str(i) for i in range(len(df))]


target_row_index = 0
for i in range(len(df_raw)):
    if '客戶編號' in df_raw.iloc[i].astype(str).values:
        target_row_index = i
        break

df = df_raw.iloc[target_row_index + 1:].copy()
df.columns = df_raw.iloc[target_row_index].astype(str).values
df.reset_index(drop=True, inplace=True)


def split_address(addr):
    addr = str(addr)
    if '區' in addr:
        return addr.partition('區')[0] + '區'
    return addr


df['客戶名稱'] = ['VIP_' + str(i) for i in range(len(df))]
df['送貨地址'] = df['送貨地址'].apply(split_address)


df.columns = [col if col != 'nan' else f'Unnamed_{i}' for i, col in enumerate(df.columns)]


save_path = '/content/drive/MyDrive/資料分析/gas/done/客戶資料.csv'


df.to_csv(save_path, index=False, encoding='utf-8-sig')

print(f"✅ 報表已成功存檔至：{save_path}")