# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CP_c1u2O1ldLLDdyFpY-49TzMkmfxQag
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import urllib.request
import os


font_url = 'https://github.com/google/fonts/raw/main/ofl/notosanstc/NotoSansTC%5Bwght%5D.ttf'
font_path = 'NotoSansTC.ttf'

if not os.path.exists(font_path):
    print("正在下載中文字體...")
    urllib.request.urlretrieve(font_url, font_path)

fe = fm.FontEntry(fname=font_path, name='NotoSansTC')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = fe.name
plt.rcParams['axes.unicode_minus'] = False

plt.rcParams['font.weight'] = 'bold'

file_path = '/content/drive/MyDrive/資料分析/gas/銷售訂單.csv'
save_dir = '/content/drive/MyDrive/資料分析/gas/done'
save_name = '年度銷售額.png'
full_save_path = os.path.join(save_dir, save_name)

try:
    df = pd.read_csv(file_path, encoding='utf-8-sig')
    df['訂單日期'] = pd.to_datetime(df['訂單日期'])
    df['年份'] = df['訂單日期'].dt.year
    yearly_sales = df.groupby('年份')['小計'].sum().reset_index().sort_values('年份')

    plt.figure(figsize=(10, 6))


    bars = plt.bar(yearly_sales['年份'].astype(str), yearly_sales['小計'],
                   color='#008B8B', edgecolor='none', alpha=1)


    plt.title('年度銷售額', fontsize=20, fontweight=900, pad=20)
    plt.xlabel('年份', fontsize=14, fontweight='bold')
    plt.ylabel('銷售額 (元)', fontsize=14, fontweight='bold')

    plt.xticks(fontsize=12, fontweight='bold')
    plt.yticks(fontsize=12, fontweight='bold')

    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + (height*0.01),
                 f'{int(height):,}', ha='center', va='bottom',
                 fontsize=11, fontweight='bold')

    plt.grid(axis='y', linestyle='--', alpha=0.3)
    plt.tight_layout()


    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    plt.savefig(full_save_path, dpi=300, bbox_inches='tight')
    print(f"💾 圖表已成功存檔至：{full_save_path}")


    plt.show()

except Exception as e:
    print(f"❌ 發生錯誤: {e}")

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import urllib.request
import os


font_url = 'https://github.com/google/fonts/raw/main/ofl/notosanstc/NotoSansTC%5Bwght%5D.ttf'
font_path = 'NotoSansTC.ttf'
if not os.path.exists(font_path):
    urllib.request.urlretrieve(font_url, font_path)

fe = fm.FontEntry(fname=font_path, name='NotoSansTC')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = fe.name
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.weight'] = 'bold'


file_path = '.csv'
save_path = '.png'

try:
    df = pd.read_csv(file_path, encoding='utf-8-sig')
    df['訂單日期'] = pd.to_datetime(df['訂單日期'])


    monthly_sales = df.groupby(df['訂單日期'].dt.to_period('M'))['小計'].sum().reset_index()
    monthly_sales = monthly_sales.sort_values('訂單日期')


    new_labels = []
    for dt in monthly_sales['訂單日期']:
        if dt.month == 1:
            new_labels.append(f"1\n{dt.year}")
        else:
            new_labels.append(str(dt.month))


    plt.figure(figsize=(15, 6))


    plt.plot(range(len(monthly_sales)), monthly_sales['小計'],
             color='#008B8B', marker='o', linewidth=3, markersize=6, alpha=1)

    plt.title('每月營業額趨勢', fontsize=22, fontweight='bold', pad=30)
    plt.ylabel('銷售額 (元)', fontsize=14, fontweight='bold')


    plt.xticks(range(len(monthly_sales)), new_labels, fontsize=11, fontweight='bold')
    plt.yticks(fontsize=12, fontweight='bold')


    plt.xlabel('  ', loc='right')
    plt.annotate('(月)', xy=(1, 0), xycoords='axes fraction',
                 xytext=(20, -15), textcoords='offset points',
                 ha='left', va='top', fontsize=12, fontweight='bold')


    ax = plt.gca()
    for label in ax.get_xticklabels():
        if "\n" in label.get_text():
            label.set_color('#004d4d')
            label.set_fontsize(12)

    plt.grid(axis='y', linestyle='--', alpha=0.3)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()


    save_dir = os.path.dirname(save_path)
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"✅ 極簡趨勢圖已成功存檔至：{save_path}")
    plt.show()

except Exception as e:
    print(f"❌ 發生錯誤: {e}")

import pandas as pd
import matplotlib.pyplot as plt
import os


df_clean = df.dropna(subset=['送貨地址']).copy()
districts = ['中西區', '北區', '安平區', '南區', '東區', '安南區', '永康區']

def get_district(address):
    for d in districts:
        if d in str(address):
            return d
    return None

df_clean['行政區'] = df_clean['送貨地址'].apply(get_district)
df_clean = df_clean.dropna(subset=['行政區'])


df_clean['訂單日期'] = pd.to_datetime(df_clean['訂單日期'])
df_clean['年份'] = df_clean['訂單日期'].dt.year
years = sorted(df_clean['年份'].dropna().unique())
num_years = len(years)


if num_years == 0:
    print("❌ 無法繪製圖表：資料中沒有有效的年份。")
else:
    fig, axes = plt.subplots(1, num_years, figsize=(7 * num_years, 7))
    if num_years == 1:
        axes = [axes]


    vibrant_colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#e377c2', '#17becf']

    for i, year in enumerate(years):
        df_year = df_clean[df_clean['年份'] == year]
        unique_customers = df_year.drop_duplicates(subset=['客戶編號'])
        plot_data = unique_customers['行政區'].value_counts().reindex(districts).fillna(0)

        wedges, texts, autotexts = axes[i].pie(
            plot_data,
            autopct='%1.1f%%',
            startangle=90,
            colors=vibrant_colors,
            pctdistance=0.75,
            shadow=False
        )
        plt.setp(autotexts, fontweight='bold', fontsize=12, color='white')
        axes[i].set_title(f'{int(year)} 年度\n(有效客戶數: {int(plot_data.sum())} 人)',
                          fontsize=18, fontweight='bold', pad=15)

    fig.legend(wedges, districts,
               title="行政區域",
               loc="lower center",
               bbox_to_anchor=(0.5, 0.05),
               ncol=7,
               fontsize=12,
               prop={'weight': 'bold'})

    plt.suptitle('年度各行政區客戶數佔比 (排除地址不明)', fontsize=24, fontweight='bold', y=1.02)
    plt.tight_layout(rect=[0, 0.12, 1, 0.95])


    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"✅ 圓餅對照圖已成功存檔至：{save_path}")

    plt.show()


print("\n📊 各年度區域客戶數統計表：")
if not df_clean.empty and '年份' in df_clean.columns:
    summary_table = df_clean.drop_duplicates(subset=['年份', '客戶編號']).groupby(['年份', '行政區']).size().unstack(fill_value=0)
    summary_table = summary_table.reindex(columns=districts, fill_value=0)
    print(summary_table)

import pandas as pd
import matplotlib.pyplot as plt
import os


if not os.path.exists(save_dir):
    os.makedirs(save_dir)


df_clean = df.dropna(subset=['送貨地址']).copy()
districts = ['中西區', '北區', '安平區', '南區', '東區', '安南區', '永康區']

def get_district(address):
    for d in districts:
        if d in str(address):
            return d
    return None

df_clean['行政區'] = df_clean['送貨地址'].apply(get_district)
df_clean = df_clean.dropna(subset=['行政區'])


df_clean['訂單日期'] = pd.to_datetime(df_clean['訂單日期'])
df_clean = df_clean.dropna(subset=['訂單日期'])
df_clean['年份'] = df_clean['訂單日期'].dt.year.astype(int)


sales_pivot = df_clean.pivot_table(
    index='年份',
    columns='行政區',
    values='小計',
    aggfunc='sum'
).reindex(columns=districts)


morandi_colors = ['#8E9775', '#E28E8E', '#7D9D9C', '#94B49F', '#B4CFB0', '#A7D2CB', '#CDBBA7']
fig, ax = plt.subplots(figsize=(12, 7))


year_labels = [str(int(y)) for y in sales_pivot.index]

sales_pivot.plot(
    kind='bar',
    ax=ax,
    width=0.8,
    color=morandi_colors,
    edgecolor='none'
)


plt.title('各年度行政區銷售總額趨勢', fontsize=18, fontweight='bold', pad=20, color='#4A4A4A')
plt.xlabel('年份 (西元)', fontsize=12, fontweight='bold', color='#4A4A4A')
plt.ylabel('銷售總額 (元)', fontsize=12, fontweight='bold', color='#4A4A4A')


ax.set_xticklabels(year_labels, rotation=0, fontsize=11, fontweight='bold')


ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.grid(axis='y', linestyle='-', alpha=0.15)
plt.legend(title='行政區域', bbox_to_anchor=(1.02, 1), loc='upper left', frameon=False)
plt.tight_layout()

plt.savefig(save_path, dpi=300, bbox_inches='tight')
print(f"✅ 莫蘭迪風格長條圖已成功存檔至：{save_path}")
plt.show()


print("\n📊 統計數值表：")
print(sales_pivot.fillna(0).astype(int))